apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-host-app-tekton
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/test-host/overlays/tekton
    repoURL: https://github.com/jdubrick-ai/test-host-gitops.git
    targetRevision: main
  destination:
    namespace: rhdh-app
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
